name: CD

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: public
        env:
          GITHUB_TOKEN: ${{github.token}}
